theme: jekyll-theme-minimal
description: Steven Popkin's Tech Site
image:
  source: images/portraits-reduced.jpg
  output: generated
  presets:
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 300
    half:
      width: 400
      height: 400
