theme: jekyll-theme-minimal
description: Steven Popkin's Tech Site
navbar-links:
  About Me: "aboutme"
  Home: "index"
  Projects: "projects"
  Contact Information: "contact"

avatar: "images/portrait-reduced.jpg"
